version: '3.7'

services:
  pg:
    container_name: sphinx-pg
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sphinx
    ports:
      - 5432:5432

  redis:
    container_name: sphinx-redis
    image: redis:7-alpine
    ports:
      - 6379:6379

  mailhog:
    container_name: sphinx-mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025  # SMTP port
      - 8025:8025  # Web UI port

  hermes:
    container_name: sphinx-hermes
    image: docker.elevendragons.com/hermes:latest
    environment:
      - API_KEY=topsecret
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
    ports:
      - 8081:8080
    depends_on:
      - mailhog