apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ template "sphinx.prefix" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}
    app.kubernetes.io/version: {{ template "sphinx.version" . }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}
        app.kubernetes.io/version: {{ template "sphinx.version" . }}
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      {{- if .Values.prometheus.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-server
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        envFrom:
        - secretRef:
          {{- if empty .Values.secret.existentName }}
            name: {{ template "sphinx.secretName" . }}
          {{- else }}
            name: {{ .Values.secret.existentName }}
          {{- end }}
        - configMapRef:
            name: {{ template "sphinx.configMapName" . }} 
      imagePullSecrets:
      - name: {{ .Values.api.imagePullSecretName }} 