apiVersion: v1
kind: Service
metadata:
  name: {{ template "sphinx.serviceName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}
    app.kubernetes.io/version: {{ template "sphinx.version" . }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}
  ports:
    - port: 80
      targetPort: 8080
  {{- if and (empty .Values.ingress.className) (not (empty .Values.serviceType)) }}
  type: {{ .Values.serviceType }}
  {{- end }}