apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "api.configMapName" . }}
data:
  {{- with (first .Values.ingress.rules) }}
  HOST: {{ .host }}
  {{- end }}
  APP_NAME: {{ .Values.configMap.appName }}
  MAX_CONCURRENT_SESSIONS: {{ .Values.configMap.maxConcurrentSessions | quote }}
  FALLBACK_LANGUAGE: {{ .Values.configMap.fallbackLanguage }}
  JWT_ACCESS_LIFETIME_IN_SEC: {{ .Values.configMap.jwtAccessLifetimeInSec | quote }}
  JWT_REFRESH_LIFETIME_IN_SEC: {{ .Values.configMap.jwtRefreshLifetimeInSec | quote }}
  HERMES_BASE_URL: {{ .Values.configMap.hermesBaseUrl }}
  CLIENT_URI_DATA_VERIFICATION: {{ .Values.configMap.clientUriDataVerification }}
  CLIENT_URI_PASSWORD_RESET: {{ .Values.configMap.clientUriPasswordReset }}