{{- if empty .Values.secret.existentName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "api.secretName" . }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.databaseUrl | b64enc | quote }}
  ROOT_APP_TOKEN: {{ .Values.secret.rootAppToken | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  HERMES_API_KEY: {{ .Values.secret.hermesApiKey | b64enc | quote }}
{{- end }}