apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "api.configMapName" . }}
data:
  {{- with (first .Values.ingress.rules) }}
  HOST: https://{{ .host }}
  {{- end }}
  APP_NAME: {{ .Values.configMap.appName }}
  APP_STYLE_URL: {{ .Values.configMap.appStyleUrl }}
  APP_LOGO_URL: {{ .Values.configMap.appLogoUrl }}
  MAX_CONCURRENT_SESSIONS: {{ .Values.configMap.maxConcurrentSessions | quote }}
  FALLBACK_LANGUAGE: {{ .Values.configMap.fallbackLanguage }}
  AUTH_GRANT_LIFETIME_IN_SEC: {{ .Values.configMap.authGrantLifetimeInSec | quote }}
  JWT_ACCESS_LIFETIME_IN_SEC: {{ .Values.configMap.jwtAccessLifetimeInSec | quote }}
  JWT_REFRESH_LIFETIME_IN_SEC: {{ .Values.configMap.jwtRefreshLifetimeInSec | quote }}
  HERMES_BASE_URL: {{ .Values.configMap.hermesBaseURL }}
  CLIENT_BASE_URL: {{ .Values.configMap.clientBaseURL }}
  CLIENT_DATA_VERIFICATION: {{ .Values.configMap.clientDataVerification }}
  CLIENT_PASSWORD_RESET: {{ .Values.configMap.clientPasswordReset }}