{{- if empty .Values.secret.existentName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sphinx.secretName" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}
    app.kubernetes.io/version: {{ template "sphinx.version" . }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secret.databaseURL | b64enc | quote }}
  REDIS_URL: {{ .Values.secret.redisURL | b64enc | quote }}
  ROOT_APP_ID: {{ .Values.secret.rootAppID | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
  HERMES_API_KEY: {{ .Values.secret.hermesAPIKey | b64enc | quote }}
  SWAGGER_AUTH: {{ .Values.secret.swaggerAuth | toJson | b64enc | quote }}
  EXTERNAL_AUTH_PROVIDERS: {{ .Values.secret.externalAuthProviders | toJson | b64enc | quote }}
{{- end }}