apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ template "prefix" . }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
  template:
    metadata: 
      labels:
        app: {{ .Chart.Name }}-api
        version: {{ .Chart.AppVersion }}
        component: backend
      {{- if .Values.prometheus.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        envFrom:
        - secretRef:
          {{- if empty .Values.secret.existentName }}
            name: {{ template "api.secretName" . }}
          {{- else }}
            name: {{ .Values.secret.existentName }}
          {{- end }}
        - configMapRef:
            name: {{ template "api.configMapName" . }} 
      imagePullSecrets:
      - name: {{ .Values.api.imagePullSecretName }} 