{{- if .Values.db.migration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sphinx.prefix" . }}-migrations
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}-postgres
    app.kubernetes.io/version: 16
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- range $path, $_ := .Files.Glob "migrations/*.sql" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}