{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: {{ template "prefix" . }}-db
spec:
  serviceName: {{ template "db.serviceName" . }}
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-pg
  template:
    metadata: 
      labels:
        app: {{ .Chart.Name }}-pg
    spec:
      containers:
      - name: {{ .Chart.Name }}-pg
        image: postgres:16.0
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            {{- if empty .Values.db.secret.existentName }}
              name: {{ template "db.secretName" . }}
            {{- else }}
              name: {{ .Values.db.secret.existentName }}
            {{- end }}
        {{- if not (empty .Values.db.volume.className) }}
        volumeMounts:
        - name: {{ .Values.db.volume.name }}
          mountPath: /var/lib/postgresql/data
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.db.volume.name }}
      spec:
        accessModes:
          - {{ .Values.db.volume.accessMode }}
        resources:
          requests:
            storage: {{ .Values.db.volume.size }}
        storageClassName: {{ .Values.db.volume.className }}
  {{- end }}
{{- end }}