{{- if and (.Values.db.enabled) (empty .Values.db.secret.existentName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sphinx.db.secretName" . }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}-postgres
    app.kubernetes.io/version: "16"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db.secret.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.secret.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.db.secret.database | b64enc | quote }}
{{- end }}