{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: {{ template "sphinx.prefix" . }}-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}-redis
    app.kubernetes.io/version: 7.2.5
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ template "sphinx.redis.serviceName" . }}
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}-redis
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}-redis
        app.kubernetes.io/version: 7.2.5
        app.kubernetes.io/component: cache
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-redis
        image: redis:7.2.5
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
          - name: MASTER
            value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        {{- if not (empty .Values.redis.volume.className) }}
        - mountPath: /data
          name: redis-data
        {{- end }}
        - mountPath: /redis-master
          name: config
      volumes:
        - name: config
          configMap:
            name: {{ template "sphinx.redis.configName" . }}
            items:
            - key: redis-config
              path: redis.conf
 {{- if not (empty .Values.redis.volume.className) }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/instance: {{ template "sphinx.prefix" . }}-redis
          app.kubernetes.io/component: cache
      spec:
        accessModes:
          - {{ .Values.redis.volume.accessMode }}
        resources:
          requests:
            storage: {{ .Values.redis.volume.size }}
        storageClassName: {{ .Values.redis.volume.className }}
  {{- end }}
{{- end }}