# Default values for sphinx-api.
api:
  version: latest
  replicaCount: 1
  imagePullPolicy: Always
  imagePullSecretName:

ingress:
  className:
  # Rules are only applied if className is set. 
  rules:
  - host: sphinx.com
    path: /
  # Let issuer empty to disable TLS. Enable only if cert-manager is already running in the machine 
  # along desired issuers.
  tls:
    issuer:

# Only applied if ingress className is NOT set.
# serviceType: NodePort

secret:
  # existentName:
  # If existentName is set, below configurations will not be used 
  databaseURL: postgres://postgres:postgres@sphinx-db:5432/sphinx
  redisURL: redis://redis:redis@rdb:6379/0
  rootAppID: 80cadd74-5ccd-41c4-9938-3c8961be04db
  jwtSecret: mysecret
  hermesApiKey: mysecret

configMap:
  appName: Sphinx
  supportEmail: support@example.com
  maxConcurrentSessions: 0
  fallbackLanguage: pt-br
  jwtAccessLifetimeInSec: "300"
  jwtRefreshLifetimeInSec: "15552000"
  hermesBaseURL: hermes/v1
  clientBaseURL: sphinx.com.br
  clientDataVerification: /verification
  clientPasswordReset: /password/reset

prometheus:
  # Only enable if there is a running instance of prometheus
  enabled: false

db:
  enabled: false
  replicaCount: 1
  # Below configuration is only used if db is enabled
  secret:
    # existentName:
    # If existentName is set, below configurations will not be used
    user: postgres
    password: postgres
    database: sphinx
  volume:
    # Let className empty to disable volume. Get a value accordingly to your cloud provider spec.
    className: hcloud-volumes
    name: sphinx-data 
    accessMode: ReadWriteOnce
    size: 10Gi

redis:
  enabled: false
  replicaCount: 1
  # Below configuration is only used if redis is enabled
  config:
    # existentName:
    # If existentName is set, below configurations will not be used
    user: redis
    password: redis
