// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: account.sql

package psqlrepo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO
  account (
    id,
    email,
    password,
    phone,
    username,
    document,
    is_active,
    has_email_been_verified,
    has_phone_been_verified,
    codes
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
  )
RETURNING internal_id
`

type CreateAccountParams struct {
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Username,
		arg.Document,
		arg.IsActive,
		arg.HasEmailBeenVerified,
		arg.HasPhoneBeenVerified,
		arg.Codes,
	)
	var internal_id int
	err := row.Scan(&internal_id)
	return internal_id, err
}

const getAccountByEntry = `-- name: GetAccountByEntry :one
WITH la AS (
  SELECT
    l.internal_id, l.id, l.account_id, l.application_id, l.roles, l.grantings, l.created_at, l.updated_at,
    json_agg(app.*)->0 application
  FROM
    link l
    JOIN application app ON app.internal_id = l.application_id
  GROUP BY
    l.internal_id
), sa AS (
  SELECT
    s.internal_id, s.id, s.account_id, s.application_id, s.refresh_token, s.refreshed_at, s.elapsed_minutes_between_refreshes, s.refreshes_count, s.device, s.ip, s.is_active, s.terminated_at, s.created_at, s.updated_at,
    json_agg(app.*)->0 application
  FROM
    session s
    JOIN application app ON app.internal_id = s.application_id
  WHERE
    s.is_active IS TRUE
  GROUP BY
    s.internal_id
)
SELECT
  a.internal_id, a.id, a.email, a.password, a.phone, a.username, a.document, a.is_active, a.has_email_been_verified, a.has_phone_been_verified, a.codes, a.password_updated_at, a.created_at, a.updated_at,
  json_agg(la.*) links,
  json_agg(sa.*) active_sessions
FROM
  account a
  JOIN la ON la.account_id = a.internal_id
  JOIN sa ON sa.account_id = a.internal_id 
WHERE
  a.email = $1 OR
  a.phone = $1 OR
  a.username = $1 OR
  a.document = $1
GROUP BY
  a.internal_id
`

type GetAccountByEntryRow struct {
	InternalID           int
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
	PasswordUpdatedAt    sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Links                json.RawMessage
	ActiveSessions       json.RawMessage
}

func (q *Queries) GetAccountByEntry(ctx context.Context, email string) (GetAccountByEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEntry, email)
	var i GetAccountByEntryRow
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Username,
		&i.Document,
		&i.IsActive,
		&i.HasEmailBeenVerified,
		&i.HasPhoneBeenVerified,
		&i.Codes,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Links,
		&i.ActiveSessions,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
WITH la AS (
  SELECT
    l.internal_id, l.id, l.account_id, l.application_id, l.roles, l.grantings, l.created_at, l.updated_at,
    json_agg(app.*)->0 application
  FROM
    link l
    JOIN application app ON app.internal_id = l.application_id
  GROUP BY
    l.internal_id
), sa AS (
  SELECT
    s.internal_id, s.id, s.account_id, s.application_id, s.refresh_token, s.refreshed_at, s.elapsed_minutes_between_refreshes, s.refreshes_count, s.device, s.ip, s.is_active, s.terminated_at, s.created_at, s.updated_at,
    json_agg(app.*)->0 application
  FROM
    session s
    JOIN application app ON app.internal_id = s.application_id
  WHERE
    s.is_active IS TRUE
  GROUP BY
    s.internal_id
)
SELECT
  a.internal_id, a.id, a.email, a.password, a.phone, a.username, a.document, a.is_active, a.has_email_been_verified, a.has_phone_been_verified, a.codes, a.password_updated_at, a.created_at, a.updated_at,
  json_agg(la.*) links,
  json_agg(sa.*) active_sessions
FROM
  account a
  JOIN la ON la.account_id = a.internal_id
  JOIN sa ON sa.account_id = a.internal_id
WHERE
  a.id = $1
GROUP BY
  a.internal_id
`

type GetAccountByIdRow struct {
	InternalID           int
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
	PasswordUpdatedAt    sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Links                json.RawMessage
	ActiveSessions       json.RawMessage
}

func (q *Queries) GetAccountById(ctx context.Context, id uuid.UUID) (GetAccountByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountById, id)
	var i GetAccountByIdRow
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Username,
		&i.Document,
		&i.IsActive,
		&i.HasEmailBeenVerified,
		&i.HasPhoneBeenVerified,
		&i.Codes,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Links,
		&i.ActiveSessions,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE
  account
SET
  email = $2,
  password = $3,
  phone = $4,
  username = $5,
  document = $6,
  is_active = $7,
  has_email_been_verified = $8,
  has_phone_been_verified = $9,
  codes = $10,
  password_updated_at = $11,
  updated_at = $12
WHERE
  id = $1
`

type UpdateAccountParams struct {
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
	PasswordUpdatedAt    sql.NullTime
	UpdatedAt            time.Time
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Username,
		arg.Document,
		arg.IsActive,
		arg.HasEmailBeenVerified,
		arg.HasPhoneBeenVerified,
		arg.Codes,
		arg.PasswordUpdatedAt,
		arg.UpdatedAt,
	)
	return err
}
