// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: account.sql

package psqlrepo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO
  account (
    id,
    email,
    password,
    phone,
    username,
    document,
    is_active,
    has_email_been_verified,
    has_phone_been_verified,
    codes
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
  )
RETURNING internal_id
`

type CreateAccountParams struct {
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Username,
		arg.Document,
		arg.IsActive,
		arg.HasEmailBeenVerified,
		arg.HasPhoneBeenVerified,
		arg.Codes,
	)
	var internal_id int
	err := row.Scan(&internal_id)
	return internal_id, err
}

const getAccountByEntry = `-- name: GetAccountByEntry :one
SELECT
  a.internal_id, a.id, a.email, a.password, a.phone, a.username, a.document, a.is_active, a.has_email_been_verified, a.has_phone_been_verified, a.codes, a.password_updated_at, a.created_at, a.updated_at,
  json_agg(l.*) links,
  json_agg(s.*) active_sessions
FROM
  account a
  LEFT JOIN session s ON s.account_id = a.id AND s.is_active IS TRUE
  LEFT JOIN link l ON l.account_id = a.id 
WHERE
  a.email = $1 OR
  a.phone = $1 OR
  a.username = $1 OR
  a.document = $1
GROUP BY
  a.id
`

type GetAccountByEntryRow struct {
	InternalID           int
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
	PasswordUpdatedAt    sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Links                json.RawMessage
	ActiveSessions       json.RawMessage
}

func (q *Queries) GetAccountByEntry(ctx context.Context, email string) (GetAccountByEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEntry, email)
	var i GetAccountByEntryRow
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Username,
		&i.Document,
		&i.IsActive,
		&i.HasEmailBeenVerified,
		&i.HasPhoneBeenVerified,
		&i.Codes,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Links,
		&i.ActiveSessions,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT
  a.internal_id, a.id, a.email, a.password, a.phone, a.username, a.document, a.is_active, a.has_email_been_verified, a.has_phone_been_verified, a.codes, a.password_updated_at, a.created_at, a.updated_at,
  json_agg(l.*) links,
  json_agg(s.*) active_sessions
FROM
  account a
  LEFT JOIN session s ON s.account_id = a.id AND s.is_active IS TRUE
  LEFT JOIN link l ON l.account_id = a.id 
WHERE
  a.id = $1
GROUP BY
  a.id
`

type GetAccountByIdRow struct {
	InternalID           int
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
	PasswordUpdatedAt    sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
	Links                json.RawMessage
	ActiveSessions       json.RawMessage
}

func (q *Queries) GetAccountById(ctx context.Context, id uuid.UUID) (GetAccountByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountById, id)
	var i GetAccountByIdRow
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Username,
		&i.Document,
		&i.IsActive,
		&i.HasEmailBeenVerified,
		&i.HasPhoneBeenVerified,
		&i.Codes,
		&i.PasswordUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Links,
		&i.ActiveSessions,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE
  account
SET
  email = $2,
  password = $3,
  phone = $4,
  username = $5,
  document = $6,
  is_active = $7,
  has_email_been_verified = $8,
  has_phone_been_verified = $9,
  codes = $10,
  password_updated_at = $11,
  updated_at = $12
WHERE
  id = $1
`

type UpdateAccountParams struct {
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
	PasswordUpdatedAt    sql.NullTime
	UpdatedAt            time.Time
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Username,
		arg.Document,
		arg.IsActive,
		arg.HasEmailBeenVerified,
		arg.HasPhoneBeenVerified,
		arg.Codes,
		arg.PasswordUpdatedAt,
		arg.UpdatedAt,
	)
	return err
}
