// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: application.sql

package psqlrepo

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO
  application (
    id,
    name,
    grantings
  )
VALUES
  (
    $1,
    $2,
    $3
  )
RETURNING internal_id
`

type CreateApplicationParams struct {
	ID        uuid.UUID
	Name      string
	Grantings []string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (int, error) {
	row := q.db.QueryRowContext(ctx, createApplication, arg.ID, arg.Name, pq.Array(arg.Grantings))
	var internal_id int
	err := row.Scan(&internal_id)
	return internal_id, err
}

const getApplicationById = `-- name: GetApplicationById :one
SELECT
  internal_id, id, name, grantings, created_at, updated_at
FROM
  application
WHERE
  id = $1
`

func (q *Queries) GetApplicationById(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationById, id)
	var i Application
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.Name,
		pq.Array(&i.Grantings),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE
  application
SET
  name = $2,
  grantings = $3
WHERE
  id = $1
`

type UpdateApplicationParams struct {
	ID        uuid.UUID
	Name      string
	Grantings []string
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.ExecContext(ctx, updateApplication, arg.ID, arg.Name, pq.Array(arg.Grantings))
	return err
}
