// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: link.sql

package psqlrepo

import (
	"context"
	"encoding/json"
)

const upsertLinks = `-- name: UpsertLinks :exec
INSERT INTO
  link(
    id,
    account_id,
    application_id,
    roles,
    grantings,
    oauth_code,
    oauth_expires_at,
    created_at,
    updated_at
  )
  SELECT 
    l.id,
    l.account_id,
    l.application_id,
    l.roles,
    l.grantings,
    l.oauth_code,
    l.oauth_expires_at,
    l.created_at,
    l.updated_at
  FROM 
    json_populate_recordset(null::link, $1) as l
ON CONFLICT (id)
DO UPDATE 
  SET
    roles = EXCLUDED.roles,
    grantings = EXCLUDED.grantings,
    updated_at = EXCLUDED.updated_at
`

func (q *Queries) UpsertLinks(ctx context.Context, fromJson json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, upsertLinks, fromJson)
	return err
}
