// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package psqlrepo

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	InternalID           int
	ID                   uuid.UUID
	Email                string
	Password             string
	Phone                sql.NullString
	Username             sql.NullString
	Document             sql.NullString
	IsActive             bool
	HasEmailBeenVerified bool
	HasPhoneBeenVerified bool
	Codes                json.RawMessage
	PasswordUpdatedAt    sql.NullTime
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Application struct {
	InternalID          int
	ID                  uuid.UUID
	Name                string
	Grantings           []string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Secret              string
	AllowedRedirectUris []string
}

type Link struct {
	InternalID     int
	ID             uuid.UUID
	AccountID      int
	ApplicationID  int
	Roles          []string
	Grantings      []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OauthCode      sql.NullString
	OauthExpiresAt sql.NullTime
}

type Session struct {
	InternalID                     int
	ID                             uuid.UUID
	AccountID                      int
	ApplicationID                  int
	RefreshToken                   sql.NullString
	RefreshedAt                    sql.NullTime
	ElapsedMinutesBetweenRefreshes []int
	RefreshesCount                 int
	Device                         string
	Ip                             string
	IsActive                       sql.NullBool
	TerminatedAt                   sql.NullTime
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}
