// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: session.sql

package psqlrepo

import (
	"context"
	"encoding/json"
)

const upsertSessions = `-- name: UpsertSessions :exec
INSERT INTO
  session(
    id,
    account_id,
    application_id,
    refresh_token,
    refreshed_at,
    elapsed_minutes_between_refreshes,
    refreshes_count,
    device,
    ip,
    is_active,
    terminated_at,
    created_at,
    updated_at
  )
  SELECT 
    l.id,
    l.account_id,
    l.application_id,
    l.refresh_token,
    l.refreshed_at,
    l.elapsed_minutes_between_refreshes,
    l.refreshes_count,
    l.device,
    l.ip,
    l.is_active,
    l.terminated_at,
    l.created_at,
    l.updated_at
  FROM 
    json_populate_recordset(null::session, $1) as l
ON CONFLICT (id)
DO UPDATE 
  SET
    refresh_token = EXCLUDED.refresh_token,
    refreshed_at = EXCLUDED.refreshed_at,
    elapsed_minutes_between_refreshes = EXCLUDED.elapsed_minutes_between_refreshes,
    refreshes_count = EXCLUDED.refreshes_count,
    device = EXCLUDED.device,
    ip = EXCLUDED.ip,
    is_active = EXCLUDED.is_active,
    terminated_at = EXCLUDED.terminated_at,
    updated_at = EXCLUDED.updated_at
`

func (q *Queries) UpsertSessions(ctx context.Context, fromJson json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, upsertSessions, fromJson)
	return err
}
